### ISSUE TITLE
Show Streaming Response

### ISSUE THREAD

**Issue by slavakurilyak** [tonykipkemboi/trip_planner_agent#2]
It would be great to see this UI be updated in real-time by streaming tokens as AI agents are performing tasks

<img width="555" alt="Screen Shot 2024-02-28 at 8 25 13 PM" src="https://github.com/tonykipkemboi/trip_planner_agent/assets/6625584/196166a6-53b1-47c1-a739-cd4f38683163">

**Comment by tonykipkemboi** [comment]
Absolutely, I haven't got around to play around with that functionality but will prioritise to get it working soon. 

Thanks!

**Comment by tonykipkemboi** [comment]
@slavakurilyak, I have updated the code to stream the output to the app and have linked the video for walkthrough purposes as well.

https://youtu.be/nKG_kbQUDDE

**Comment by EchoSilo** [comment]
Great addition, I've been looking for this code. It seems it's not pulling/grabbing all of the responses from the llm though. You code is only showing the latter outputs as opposed to all of them, is this on purpose. For example, the repo you referred to from https://github.com/joaomdmoura/crewAI/pull/333 seems to be more robust in grabbing messages.

**Comment by tonykipkemboi** [comment]
Hi @EchoSilo,

Glad you found it useful. 

This code was a quick implementation using the direct callback parameter in the agents. I did not give it much time to polish all the outputs and do a full cross-check vs repl but it actually outputs majority of the actions happening behind the scenes from the agents. Can you share an example of text that is not outputted? I know the switching chains is one of them.

Also, to note, my code did not use the LangChain callback handler instance; rather, I created a custom callback handler and used that instead. The goal was to get it out there quickly in an easy-to-understand way. I will put some work into creating one with the LangChain callback handler, which should be better theoretically.

**Comment by EchoSilo** [comment]
Hey tony no criticism, this code is really helpful. I also found something [here](https://github.com/AbubakrChan/crewai-business-product-launch/blob/2ab75adc4f8f3e4c36062db53e482b58866e0131/main.py#L211) that was interesting, in the StreamExpander class. I put it in the st.status and it works well for getting more messages out.

**Comment by tonykipkemboi** [comment]
@EchoSilo, this is great! Yes, there's definitely many way to get the output on the screen. Your implementation is spot on and will give it a try. Thanks for sharing!
