### ISSUE TITLE
nltk_data

### ISSUE THREAD

**Issue by arjunkrishna** [tonykipkemboi/trip_planner_agent#3]
have you noticed that sometimes, this agent tries to download punkt package. Why is that?  Could this download a virus like this or is this expected in this code.

This is the log

"
Action: Scrape website content
Action Input: {"website": "https://www.tripadvisor.com/Attractions-g33845-Activities-zft11306-Mystic_Mystic_Country_Connecticut.html"}[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\arjun\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

I encountered an error while trying to use the tool. This was the error: 1 validation error for Task
"

**Comment by tonykipkemboi** [comment]
Interesting, @arjunkrishna. Haven't noticed it yet but will investigate.

**Comment by sfc-gh-tkipkemboi** [comment]
So, this seems to be coming from an Unstructured package. I haven't fully dove into why it needs it though.

**Comment by arjunkrishna** [comment]
Thanks for checking. Do not put anymore time looking into it. It was just out of curiosity that I had asked.

**Comment by tonykipkemboi** [comment]
@arjunkrishna, actually found this to be related to Unstructured's `tokenize.py` function which downloads the `nltk` function if not present, so this is not the agent downloading the package. I also found an issue where someone mentioned that it was interfering with their observability logs. So I opened a PR on Unstructured to quite these logs. Thanks for pointing it out!
